
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND APPEND ASSIGN BOOLEAN CADENA COMA COMILLAS COMILLASSIMPLES COMMENT COMMENTS CORCHETEDER CORCHETEIZQ DEF DIFERENTE DIVIDE DIVISIONENTERA DOSPUNTOS ELSE EQUALS EXPONENTE FLOAT FOR ID IF IN INPUT IS LESSTHAN LLAVEDER LLAVEIZQ LPAREN MAYORIGUAL MENORIGUAL MINUS MOD MORETHAN NOT NOTS NUMBER OPEN OR PLUS PRINT PUNTO PUNTOCOMA RANGE REMOVE RETURN RPAREN STRING SUBGUION TIMES WHILEcuerpo : expression\n              | comentario\n              | asignacion\n              | valoresComa\n              | lista\n              expression : expression PLUS termexpression : expression MINUS termexpression : termterm : term TIMES factorterm : term DIVIDE factorterm : factorfactor : NUMBER\n              | STRING\n              | FLOAT\n              | CADENAfactor : LPAREN expression RPARENcomentario : COMMENT\n                 | COMMENTSasignacion : ID ASSIGN expression\n                  | multipleAsignacion expression\n                  | ID ASSIGN BOOLEAN\n                  | ID ASSIGN listamultipleAsignacion : ID ASSIGN \n                          | ID ASSIGN multipleAsignacion \n                          valoresComa : factor\n                   | valoresComa COMA factorlista : CORCHETEIZQ valoresComa CORCHETEDER'
    
_lr_action_items = {'COMMENT':([0,],[8,]),'COMMENTS':([0,],[9,]),'ID':([0,24,42,],[10,35,35,]),'CORCHETEIZQ':([0,24,],[13,13,]),'NUMBER':([0,11,13,18,19,20,21,22,23,24,39,42,],[14,14,14,14,14,14,14,14,14,14,-24,-23,]),'STRING':([0,11,13,18,19,20,21,22,23,24,39,42,],[15,15,15,15,15,15,15,15,15,15,-24,-23,]),'FLOAT':([0,11,13,18,19,20,21,22,23,24,39,42,],[16,16,16,16,16,16,16,16,16,16,-24,-23,]),'CADENA':([0,11,13,18,19,20,21,22,23,24,39,42,],[17,17,17,17,17,17,17,17,17,17,-24,-23,]),'LPAREN':([0,11,13,18,19,20,21,22,23,24,39,42,],[18,18,18,18,18,18,18,18,18,18,-24,-23,]),'$end':([1,2,3,4,5,6,7,8,9,12,14,15,16,17,25,26,30,31,32,33,34,36,37,38,40,41,],[0,-1,-2,-3,-4,-5,-8,-17,-18,-11,-12,-13,-14,-15,-20,-11,-6,-7,-26,-9,-10,-19,-21,-22,-27,-16,]),'PLUS':([2,7,12,14,15,16,17,25,26,29,30,31,33,34,36,41,],[19,-8,-11,-12,-13,-14,-15,19,-11,19,-6,-7,-9,-10,19,-16,]),'MINUS':([2,7,12,14,15,16,17,25,26,29,30,31,33,34,36,41,],[20,-8,-11,-12,-13,-14,-15,20,-11,20,-6,-7,-9,-10,20,-16,]),'COMA':([5,12,14,15,16,17,27,28,32,41,],[21,-25,-12,-13,-14,-15,21,-25,-26,-16,]),'RPAREN':([7,14,15,16,17,26,29,30,31,33,34,41,],[-8,-12,-13,-14,-15,-11,41,-6,-7,-9,-10,-16,]),'TIMES':([7,12,14,15,16,17,26,30,31,33,34,41,],[22,-11,-12,-13,-14,-15,-11,22,22,-9,-10,-16,]),'DIVIDE':([7,12,14,15,16,17,26,30,31,33,34,41,],[23,-11,-12,-13,-14,-15,-11,23,23,-9,-10,-16,]),'ASSIGN':([10,35,],[24,42,]),'CORCHETEDER':([14,15,16,17,27,28,32,41,],[-12,-13,-14,-15,40,-25,-26,-16,]),'BOOLEAN':([24,],[37,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cuerpo':([0,],[1,]),'expression':([0,11,18,24,],[2,25,29,36,]),'comentario':([0,],[3,]),'asignacion':([0,],[4,]),'valoresComa':([0,13,],[5,27,]),'lista':([0,24,],[6,38,]),'term':([0,11,18,19,20,24,],[7,7,7,30,31,7,]),'multipleAsignacion':([0,24,42,],[11,39,39,]),'factor':([0,11,13,18,19,20,21,22,23,24,],[12,26,28,26,26,26,32,33,34,26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cuerpo","S'",1,None,None,None),
  ('cuerpo -> expression','cuerpo',1,'p_cuerpo','sintatico.py',6),
  ('cuerpo -> comentario','cuerpo',1,'p_cuerpo','sintatico.py',7),
  ('cuerpo -> asignacion','cuerpo',1,'p_cuerpo','sintatico.py',8),
  ('cuerpo -> valoresComa','cuerpo',1,'p_cuerpo','sintatico.py',9),
  ('cuerpo -> lista','cuerpo',1,'p_cuerpo','sintatico.py',10),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','sintatico.py',15),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','sintatico.py',19),
  ('expression -> term','expression',1,'p_expression_term','sintatico.py',23),
  ('term -> term TIMES factor','term',3,'p_term_times','sintatico.py',27),
  ('term -> term DIVIDE factor','term',3,'p_term_div','sintatico.py',31),
  ('term -> factor','term',1,'p_term_factor','sintatico.py',35),
  ('factor -> NUMBER','factor',1,'p_factor_num','sintatico.py',39),
  ('factor -> STRING','factor',1,'p_factor_num','sintatico.py',40),
  ('factor -> FLOAT','factor',1,'p_factor_num','sintatico.py',41),
  ('factor -> CADENA','factor',1,'p_factor_num','sintatico.py',42),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','sintatico.py',46),
  ('comentario -> COMMENT','comentario',1,'p_comentario','sintatico.py',50),
  ('comentario -> COMMENTS','comentario',1,'p_comentario','sintatico.py',51),
  ('asignacion -> ID ASSIGN expression','asignacion',3,'p_asignacion','sintatico.py',55),
  ('asignacion -> multipleAsignacion expression','asignacion',2,'p_asignacion','sintatico.py',56),
  ('asignacion -> ID ASSIGN BOOLEAN','asignacion',3,'p_asignacion','sintatico.py',57),
  ('asignacion -> ID ASSIGN lista','asignacion',3,'p_asignacion','sintatico.py',58),
  ('multipleAsignacion -> ID ASSIGN','multipleAsignacion',2,'p_multipleAsignacion','sintatico.py',62),
  ('multipleAsignacion -> ID ASSIGN multipleAsignacion','multipleAsignacion',3,'p_multipleAsignacion','sintatico.py',63),
  ('valoresComa -> factor','valoresComa',1,'p_valoresComa','sintatico.py',67),
  ('valoresComa -> valoresComa COMA factor','valoresComa',3,'p_valoresComa','sintatico.py',68),
  ('lista -> CORCHETEIZQ valoresComa CORCHETEDER','lista',3,'p_lista','sintatico.py',72),
]
